language: java
jdk:
  - oraclejdk8

env:
  - COVERAGE=0.3

before_install:
  # execute all of the commands which need to be executed
  # before installing dependencies
  - pwd
  - ls -la

install:
  # install all of the dependencies you need here
  - ./gradlew clean jar

before_script:
  # execute all of the commands which need to be executed
  # before running actual tests

script:
  # execute all of the commands which should make the build pass or fail
  - COVERAGE=0.057 ./gradlew -p ./monolithic/ui check
  - COVERAGE=0.148 ./gradlew -p ./monolithic/service/cart check
  - COVERAGE=0.0 ./gradlew -p ./monolithic/service/user check
  - COVERAGE=0.397 ./gradlew -p ./monolithic/repository/order check
  - COVERAGE=0.0 ./gradlew -p ./monolithic/repository/cart check
  - COVERAGE=0.124 ./gradlew -p ./monolithic/repository/product check
  - COVERAGE=0.318 ./gradlew -p ./monolithic/repository/user check

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

