anguage: java
jdk:
  - oraclejdk8

before_install:
  # execute all of the commands which need to be executed
  # before installing dependencies
  - pwd
  - ls -la

install:
  # install all of the dependencies you need here

before_script:
  # execute all of the commands which need to be executed
  # before running actual tests
  - ./gradlew clean jar

script:
  # execute all of the commands which should make the build pass or fail
  - ./gradlew test