language: java
jdk:
  - oraclejdk8
  - oraclejdk9

# Had a look how this was done by Lecturer
env:
  - COVERAGE=0.057 BUILD_TARGET=./monolithic/ui
  - COVERAGE=0.148 BUILD_TARGET=./monolithic/service/cart
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/service/user
  - COVERAGE=0.397 BUILD_TARGET=./monolithic/repository/order
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/cart
  - COVERAGE=0.124 BUILD_TARGET=./monolithic/repository/product
  - COVERAGE=0.318 BUILD_TARGET=./monolithic/repository/user


before_install:
  # execute all of the commands which need to be executed
  # before installing dependencies
  - pwd
  - ls -la

install:
  # install all of the dependencies you need here
  - ./gradlew clean jar

before_script:
  # execute all of the commands which need to be executed
  # before running actual tests

script:
  # execute all of the commands which should make the build pass or fail
  - ./gradlew -p $BUILD_TARGET check

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'