anguage: java
jdk:
  - oraclejdk8

before_install:
  # execute all of the commands which need to be executed
  # before installing dependencies
  - pwd
  - ls -la

install:
  # install all of the dependencies you need here
  - ./gradlew clean jar

before_script:
  # execute all of the commands which need to be executed
  # before running actual tests

script:
  # execute all of the commands which should make the build pass or fail
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'


# If any of the commands in the first four phases of the job lifecycle return a non-zero exit code, the build is broken:
#
#  If before_install, install or before_script returns a non-zero exit code, the build is errored and stops immediately.
#  If script returns a non-zero exit code, the build is failed, but continues to run before being marked as failed.
#  The exit code of after_success, after_failure, after_script, after_deploy and subsequent stages do not affect the build result. However, if one of these stages times out, the build is marked as failed.
