anguage: java
jdk:
  - oraclejdk8

before_install:
  # execute all of the commands which need to be executed
  # before installing dependencies
  - pwd
  - ls -la

install:
  # install all of the dependencies you need here
  - ./gradlew clean jar

before_script:
  # execute all of the commands which need to be executed
  # before running actual tests

script:
  # execute all of the commands which should make the build pass or fail
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
